title: Лингвистический Ассоциативный Эксперимент
email: dm.matveyev@gmail.com
description: >-
  Программа проведения лингвистического ассоциативного эксперимента в Интернет
  помогает ученым из сферы психолингвистики проводить исследования и сбор данных
  респондентов в более удобной форме
url: "https://greenfork.github.io/associative-experiment/"
twitter_username: mrgreenfork
github_username:  greenfork

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - plan.org
