* Page
** First screen
*** ru
Лингвистический ассоциативный эксперимент

Путь к тайнам человеческого сознания методом экспериментального
выявления ассоциативных вербальных связей
** Story
*** ru
Путь к тайнам нередко лежит через уже известные вещи, которые лишь
требуют другого взгляда, другой точки зрения или совмещения этих двух
компонентов.

В детстве, наверное, каждый играл в игру "азбука" или "цепочка", когда
нужно последовательно называть слова так, чтобы конечная буква одного слова
служила началом для другого. Например, "арбуз" - "зима" - "азбука" - ...

Некоторые же играли и в другую игру: "ассоциации". В этой игре нужно
так же последовательно называть слова, но теперь они связаны не первой
и последней буквой слова, а смыслом слова, его ассоциацией. То есть,
если я назову слово "зима", вы можете подумать о холоде и назвать
слово "холодная", или вы можете подумать о снеге и сказать "снег". А
если я назову слово "бить", вы можете вспомнить о выражении "бить
баклуши", то есть бездельничать, и сказать "баклуши".

Наверное, если долго играть в эту игру с одним человеком, то можно
будет узнать много интересного об этом человеке: что он любит, что ему
не нравится, что у него вызывает радость, что у него вызывает грусть.
Но также можно будет узнать, как думает человек: если ему сказать, что
завтра пойдет дождь, то он возьмет с собой зонт или проведет весь
следующий день в возблагодарении небес за этот дар? Вы можете подумать,
что каждый разумный человек, конечно же, возьмет зонт, но так было не
всегда. В древние времена дождь почитался, как божественная благодать,
и проводились ритуалы по вызову дождя; сегодня такой ритуал все еще
сохранился у племенных народов, в частности народов Африки.

Но это лишь один человек. И спрашивать его придется очень долго
и подробно. Было бы здорово, если бы можно было узнать о целой группе
людей сразу и спрашивать лишь небольшую часть от всех слов. И ведь так
можно сделать! Если опросить только всех мужчин или только всех женщин,
предлагая им, скажем, по одной сотой части от всех слов, то можно получить
ответы, которые с большой вероятностью окажутся правдой для всех мужчин
или всех женщин. И чем больше мы знаем о группе, то есть ее пол, возраст,
национальность и т.д., тем более правдивыми окажутся ответы.
** Scientific explanation
*** ru
Бесконечные и безумные формулы из мира статистики и лингвистики
Пока отсутствуют
** How reactions are collected
*** ru
Вам предлагается ввести свои личные данные, исключая имя и
фамилию, чтобы эксперимент проходил анонимно. Далее вы приступите к
самому эксперименту: вы увидите на экране слово и пустое поле под ним,
куда вы можете ввести свою ассоциацию. После ввода вы нажимаете клавишу
Enter и повторяете, пока не закончатся все слова.
** Visualizing data
*** ru
Представление данных в виде графа, инфографики и прочее
