* Page
** First screen
*** ru
Лингвистический ассоциативный эксперимент

Путь к тайнам человеческого сознания методом экспериментального
выявления ассоциативных вербальных связей
** Story
*** ru
Что такое лингвистический ассоциативный эксперимент?

Путь к тайнам нередко лежит через уже известные вещи, которые лишь
требуют другого взгляда, другой точки зрения или совмещения этих двух
компонентов.

В детстве, наверное, каждый играл в игру "азбука" или "цепочка", когда
нужно последовательно называть слова так, чтобы конечная буква одного слова
служила началом для другого. Например, "арбуз" - "зима" - "азбука" - ...

Некоторые же играли и в другую игру: "ассоциации". В этой игре нужно
так же последовательно называть слова, но теперь они связаны не первой
и последней буквой слова, а смыслом слова, его ассоциацией. То есть,
если я назову слово "зима", вы можете подумать о холоде и назвать
слово "холодная", или вы можете подумать о снеге и сказать "снег". А
если я назову слово "бить", вы можете вспомнить о выражении "бить
баклуши", то есть бездельничать, и сказать "баклуши".

Наверное, если долго играть в эту игру с одним человеком, то можно
будет узнать много интересного об этом человеке: что он любит, что ему
не нравится, что у него вызывает радость, что у него вызывает грусть.
Но также можно будет узнать, как думает человек: если ему сказать, что
завтра пойдет дождь, то он возьмет с собой зонт или проведет весь
следующий день в возблагодарении небес за этот дар? Вы можете подумать,
что каждый разумный человек, конечно же, возьмет зонт, но так было не
всегда. В древние времена дождь почитался, как божественная благодать,
и проводились ритуалы по вызову дождя; сегодня такой ритуал все еще
сохранился у племенных народов, в частности народов Африки.

Но это лишь один человек. И спрашивать его придется очень долго
и подробно. Было бы здорово, если бы можно было узнать о целой группе
людей сразу и спрашивать лишь небольшую часть от всех слов. И ведь так
можно сделать! Если опросить только всех мужчин или только всех женщин,
предлагая им, скажем, по одной сотой части от всех слов, то можно получить
ответы, которые с большой вероятностью окажутся правдой для всех мужчин
или всех женщин. И чем больше мы знаем о группе, то есть ее пол, возраст,
национальность и т.д., тем более правдивыми окажутся ответы.
** How is the experiment conducted?
*** ru
Как проводится эксперимент?

В ходе лингвистического ассоциативного эксперимента респонденту (так
называют того, кто проходит эксперимент) предлагается заполнить о себе
личную информацию, исключая имя и фамилию: пол, возраст, язык -- это
позволяет пройти эксперимент анонимно. Далее респондент видит перед собой
слово и поле для ввода своей ассоциации. После ввода всех слов эксперимент
считает завершенным, и респондент может честно радоваться своему вкладу в
культурное наследие своего языка!
** Why does one need it?
*** ru
Для чего нужен эксперимент?

На самом деле все просто.

Лингвистический ассоциативный эксперимент стремится создать модель
человеческого сознания на основе его ассоциаций.

А сейчас будет немного сложнее.

Тезаурус

Основным представлением данных после проведения эксперимента является
ассоциативный тезаурус. Тезаурус состоит из словарный статей. А каждая
словарная статья относится к одному стимулу и имеет таблицу с двумя
колонками: реакция и частота, где реакция -- это реакция респондента на
данный стимул, а частота обозначает, сколько раз встретилась данная
реакция.

Например:

Стимул: человек
| Реакция  | Частота |
|----------+---------|
| личность |     173 |
| добрый   |     108 |
| хороший  |      96 |
| животное |      87 |
| существо |      87 |
| ...      | ...     |

Один из вариантов построения модели сознания человека основывается на
вычленении связей между единицами сознания в психике человека. В
качестве единиц сознания могут выступать образы, эмоции, чувства,
ощущения. В случае тезауруса, единицами сознания выступают слова.
И чем больше частота реакции в словарной статье, тем сильнее ассоциативная
связь между стимулом и реакцией.

Представление сознания

Словарная статья состоит из стимула и таблицы с реакциями и частотами.
Но это лишь текстовое представление, гораздо интереснее это будет
изобразить визуально, например в качестве графа:

изображение

На графе в центре находится стимул, а от стимула расходятся реакции, причем
чем выше частота реакции, то есть чем сильнее связь, тем ближе к ядру
располагается реакция.

Все словарные статьи можно привязать к одному ядру, в котором будут указаны
особенности выборки реакций. Например, если нужно получить реакции только
тех респондентов, кому от 15 до 25 лет, татарской национальности с родным
языком татарским, проживающих в Казани. Таким образом получится
ассоциативная карта "усредненного" респондента с заданными параметрами,
которая расскажет о его устройстве мира.

Таким образом, комбинируя все возможные параметры выборки, можно
получить многомерную ассоциативную сеть, где измерениями будут служить
параметры выборки. Такая сеть расскажет во всех подробностях о
разнообразии людей и их образе мира.
* Fixme
** Design
- Margin between headers and text
- More images
- Put bottom description in the smaller box
